[package]
name = "rust-blockchain"
version = "0.1.0"
authors = ["Kendrick Grünberg <k.gruenberg@tu-braunschweig.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.3"
hex = "0.4.3"